/* 
 * @(#)Tailf.java        1.0 09/09/17
 *
 * This file has been auto-generated by JNC, the
 * Java output format plug-in of pyang.
 * Origin: module "tailf-common", revision: "2017-01-26".
 */

package com.airlenet.yang.model.tailfCommon;

import com.tailf.jnc.*;

import java.util.HashMap;

/**
 * The root class for namespace http://tail-f.com/yang/common (accessible from 
 * TailfCommon.NAMESPACE) with prefix "tailf" (TailfCommon.PREFIX).
 *
 * @version 1.0 2017-09-09
 * @author Auto Generated
 */
public class Tailf {

    public static final String NAMESPACE = "http://tail-f.com/yang/common";

    public static final String PREFIX = "tailf";

    /**
     * Enable the elements in this namespace to be aware
     * of the data model and use the generated classes.
     */
    public static void enable() throws JNCException {
        YangElement.setPackage(NAMESPACE, "com.airlenet.yang.model.tailfCommon");
        Tailf.registerSchema();
    }

    /**
     * Register the schema for this namespace in the global
     * schema table (CsTree) making it possible to lookup
     * CsNode entries for all tagpaths
     */
    public static void registerSchema() throws JNCException {
        SchemaParser parser = new SchemaParser();
        HashMap<Tagpath, SchemaNode> h = SchemaTree.create(NAMESPACE);
        parser.findAndReadFile("Tailf.schema", h, Tailf.class);
    }

}
